### ISSUE TITLE
Event 22 not displaying description

### ISSUE THREAD

**Issue by strangejschool** [strangejmaster/Billions-of-Years#4]
When trying to access Event 22 it will simply display the placeholder prefab for the event page rather than the description.

**Comment by strangejschool** [comment]
The error was caused be a syntax error in the events.txt file. The C# code to load in the Events has to have a certain syntax to parse the file and that was missing in Event 22, this should be fixed by the next build.

**Comment by strangejmaster** [comment]
As of v1.0.1 this issue is now fixed
